### ISSUE TITLE
Getting error "there was a problem loading this page. Retrying..."

### ISSUE THREAD

**Issue by sksamal** [but3k4/youtube-views#13]
python3 bot.py --visits 1 --url url --verbose
there was a problem loading this page. Retrying...
there was a problem loading this page. Retrying...
there was a problem loading this page. Retrying...

**Comment by alphanumericaltycoon** [comment]
Might be a bad proxy in the list.

I also found that disabling the proxy software on my PC also helped.

**Comment by edcarSky** [comment]
me also i have issue on running, pls help

C:\Python36\youtube-views-master>python bot.py --visits 100 --url url --proxy proxy -v
[1011/094822.105:FATAL:content_main_runner_impl.cc(520)] --single-process is not supported in chrome multiple dll browser.
Traceback (most recent call last):
  File "bot.py", line 104, in <module>
    sys.exit(_main())
  File "bot.py", line 98, in _main
    bot.run()
  File "bot.py", line 49, in run
    verbose=self.opts.verbose
  File "C:\Python36\youtube-views-master\modules\youtube.py", line 54, in __init__
    self.browser = webdriver.Chrome(options=self.options)
  File "C:\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by houssem250** [comment]
SyntaxError: invalid syntax
this what's happened when I put the data ?!

**Comment by complexvoid** [comment]
When this error will be happen your given youtube url videos views will be increase also check this!! Run this script & also open your youtube videos in background to check. Thank you!
