### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by ElectroGamesDev** [but3k4/youtube-views#2]
Do you have discord, its still not working.

 C:\Users\Tristyn\Desktop>youtube.py --visits 10 --url https://www.youtube.com/watch?v=H53BgIIaHd0&t=11s
Traceback (most recent call last):
  File "C:\Users\Tristyn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Tristyn\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Tristyn\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tristyn\Desktop\youtube.py", line 438, in <module>
    sys.exit(_main())
  File "C:\Users\Tristyn\Desktop\youtube.py", line 433, in _main
    youtube = YouTube(cli_args)
  File "C:\Users\Tristyn\Desktop\youtube.py", line 52, in __init__
    self.browser = webdriver.Chrome(options=self.options)
  File "C:\Users\Tristyn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Tristyn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

't' is not recognized as an internal or external command,
operable program or batch file.

**Comment by but3k4** [comment]
The error message is clear:

't' is not recognized as an internal or external command, operable program or batch file.

It means, your url cannot have &t=11s. So, instead of running this:

youtube.py --visits 10 --url https://www.youtube.com/watch?v=H53BgIIaHd0&t=11s

Run this:

youtube.py --visits 10 --url https://www.youtube.com/watch?v=H53BgIIaHd0
