### ISSUE TITLE
Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError

### ISSUE THREAD

**Issue by todokku** [but3k4/youtube-views#3]
**python:3.7
win:10**
**im using tor over proxy 127.0.0.1:1080(shadowsocks ws)**

**after run :**
python3 bot.py --visits 2 --url https://www.youtube.com/watch?v=XQb7BrTWtnI --proxy 127.0.0.1:9050 --enable-tor

**give error :**
[0208/193054.765:FATAL:content_main_runner_impl.cc(528)] --single-process is not supported in chrome multiple dll browser.

**& after comment line 43 of file youtube.py getting :**

DevTools listening on ws://127.0.0.1:61699/devtools/browser/e608d08f-fd40-44f9-8736-624b16440e93
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002699301DF08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9050): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002699301DF08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 67, in <module>
    sys.exit(_main())
  File "bot.py", line 63, in _main
    bot.run()
  File "bot.py", line 37, in run
    ip_address = utils.get_ipaddr(proxy=self.opts.proxy)
  File "C:\Users\Administrator\Desktop\youtube-views-master\utils.py", line 134, in get_ipaddr
    response = requests.get(url, proxies=proxies)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9050): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002699301DF08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

im using tor over proxy on port 1080
please help me 
finest regards

**Comment by but3k4** [comment]
If you are using shadowsocks ws, you cannot use the tor port, you must use the proxy port instead. I mean, you need to change this:

python3 bot.py --visits 2 --url https://www.youtube.com/watch?v=XQb7BrTWtnI --proxy 127.0.0.1:9050 --enable-tor

to this:

python3 bot.py --visits 2 --url https://www.youtube.com/watch?v=XQb7BrTWtnI --proxy 127.0.0.1:1080 --enable-tor

**Comment by todokku** [comment]
![2020-02-10_115451](https://user-images.githubusercontent.com/59433408/74132656-446c2000-4bfc-11ea-9e5b-4f757eb55db8.png)
test it & not work with :
python3 bot.py --visits 2 --url https://www.youtube.com/watch?v=XQb7BrTWtnI --proxy 127.0.0.1:1080 --enable-tor
freeze in section :
DevTools listening on ws://127.0.0.1:31815/devtools/browser/c0147c91-0c51-4ec4-9ec2-ba25f398d9c5
& in youtube link view count not change after far time

**Comment by but3k4** [comment]
I have no idea what that message means, but your views are not increasing because the bot is not working on your system (maybe an issue between the proxy and tor). As I have not used Windows since 2002 I suggest you a different approach: Try to spin up a Linux VM or a container, you can use the Windows Subsystem for Linux or VirtualBox or docker.
